version: '3.8'

services:
  family-app:
    container_name: family_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8383:8282"
    volumes:
      - "${HOST_DATA_DIR:-./data}:/data"
    env_file:
      - path: .env
        required: false
    restart: unless-stopped
